{% set name = "datefudge" %}
{% set version = "1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://deb.debian.org/debian/pool/main/d/datefudge/datefudge_{{ version }}.tar.xz
  sha256: 3f8a41760883ec13608850ad3a5374f441c7e66363eaaab5997cfe678e6e9225
  patches:
    - 0001-Make-the-Makefile-portable.patch
    # https://salsa.debian.org/debian/datefudge/-/commit/508fc0f371a5b056c1b7c9379b3446eb60af774a
    - 0002-Revert-glibc-2.31-patch.patch

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - datefudge "2003-04-01 09:42" date

about:
  home: https://packages.qa.debian.org/d/datefudge.html
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: Fake the system date

extra:
  recipe-maintainers:
    - scopatz
    - xhochy
