appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Hd/vVy1ef5QVhFn1TRSZ1iDAOnI9UZ1d+s9oXf6/PjZ34q8IjFG358gsHJPFnv7yCyrXVxz6BaWoMlOXFLu8O+gbbGFntwMT8FLiLsTq+W0Pqaz6gBw2UJJWngm4MpWrEcxcN6/IYKXE9MP8GilnmPGC83RhFp/U/fTGNh3/78cAXqHvs0YpDvB8+4gOHVPK2PcPRIwF4Ni3imTwdPJSPfalxibkTXqBf3eQONwNkPPu1/keKAcThz5rxvqIDL+WFk9FtJ76VhqUNtVU5vHmjGBA6LnqdgbHoA1v1QHQfG1hnGvCnjzZbp0sgGpJf9b0GezgO4qVKXt+AMIlPAOHfiqf8qgKb+Kwyy0tH4FivD7RaUm798HOSyVTfeVIe+6d+gn3V2kWHhmZ9XiaG/7DMJvgja1SGi8ZO97bWQXuHtvF+tF9nbPTkzM0WB+tZgBF6WTgJGBB+UFRY4CaiPp/oClHlxJWnNyPVGrFskxbntWQel3DHlNU2IxP+h4ORcFrvJ4/4BsdC1llSwzjtE23dVG3LYL+gCAL2TEXQ79xu9wHyq1FULhMFxf2041d/rY0HCUiV0eOKxIPPRq1DAG3wY1jSJHfYtJQnW5Mp/fK+fNwPKXyag1fjJMyl0zoQGomEDVmDianc3hiqMAlc+xmmdGzdb3p1g038aMIsTSQRIM=}
